### ISSUE TITLE
wrong port for health check probes

### ISSUE THREAD

**Issue by eed3si9n** [lightbend/reactive-app-maven-plugin#44]
## steps

In the integration test script comment out all tests except for Lagom one:

```bash
# it_test src/it/hello           hello:1.0
#it_test src/it/akka-quickstart akka-quickstart:1.0  || die "it_test fail"
#it_test src/it/play-endpoints  play-endpoints:1.0   || die "it_test fail"
it_test src/it/lagom-endpoints hello-impl:1.0       || die "it_test fail"
#it_test src/it/akka-cluster    akka-cluster:1.0     || die "it_test fail"
```
and then run

```bash
bin/run-integration-tests.sh -x
```

then open minikube dashboard:

```
minikube dashboard
```

## problem

http://192.168.99.104:30000/#!/overview?namespace=default

says "Readiness probe errored: strconv.Atoi: parsing "akka-mgmt-http": invalid syntax
![overview_-_kubernetes_dashboard](https://user-images.githubusercontent.com/184683/44099843-88b3f826-9fb1-11e8-9ad3-a87a277be394.jpg)
"

## notes

```
          readinessProbe:
            httpGet:
              path: "/platform-tooling/ready"
              port: "akka-mgmt-http"
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: "/platform-tooling/healthy"
              port: "akka-mgmt-http"
            periodSeconds: 10
            initialDelaySeconds: 60
```

"akka-mgmt-http" is not recognized as a port.

## alternative repro steps

```
minikube delete
minikube start
eval $(minikube docker-env)
export GPG_TTY=$(tty)
mvn -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true clean install

cd src/it/lagom-endpoints
mvn -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true clean install

rp generate-kubernetes-resources --generate-all --registry-use-local hello-impl:1.0 > hello.yml

kubectl apply --validate -f hello.yml
```

**Comment by TimMoore** [comment]
According to the docs, you can use named ports, as long as they are defined as container ports: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#use-a-named-port

Suggest doing whatever the sbt plugin does in the short term.

**Comment by TimMoore** [comment]
The sbt plugin does generate named ports for the deployment, and uses these in the probes.

Here's the YAML generated for Chirper:

```yaml
---
apiVersion: "apps/v1beta2"
kind: Deployment
metadata:
  name: "chirpservice-v1-0-0-snapshot"
  labels:
    appName: chirpservice
    appNameVersion: "chirpservice-v1-0-0-snapshot"
spec:
  replicas: 2
  selector:
    matchLabels:
      appNameVersion: "chirpservice-v1-0-0-snapshot"
  template:
    metadata:
      labels:
        appName: chirpservice
        appNameVersion: "chirpservice-v1-0-0-snapshot"
    spec:
      restartPolicy: Always
      containers:
        - name: chirpservice
          image: "chirp-impl:1.0.0-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          env:
            - name: "JAVA_OPTS"
              value: "-Dplay.http.secret.key= -Dplay.filters.hosts.allowed.0="
            - name: "RP_APP_NAME"
              value: chirpservice
            - name: "RP_APP_TYPE"
              value: lagom
            - name: "RP_APP_VERSION"
              value: "1.0.0-SNAPSHOT"
            - name: "RP_DYN_JAVA_OPTS"
              value: "-Dakka.discovery.kubernetes-api.pod-namespace=$RP_NAMESPACE"
            - name: "RP_ENDPOINTS"
              value: "HTTP,AKKA_REMOTE,AKKA_MGMT_HTTP"
            - name: "RP_ENDPOINTS_COUNT"
              value: "3"
            - name: "RP_ENDPOINT_0_BIND_HOST"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "RP_ENDPOINT_0_BIND_PORT"
              value: "10000"
            - name: "RP_ENDPOINT_0_HOST"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "RP_ENDPOINT_0_PORT"
              value: "10000"
            - name: "RP_ENDPOINT_1_BIND_HOST"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "RP_ENDPOINT_1_BIND_PORT"
              value: "10001"
            - name: "RP_ENDPOINT_1_HOST"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "RP_ENDPOINT_1_PORT"
              value: "10001"
            - name: "RP_ENDPOINT_2_BIND_HOST"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "RP_ENDPOINT_2_BIND_PORT"
              value: "10002"
            - name: "RP_ENDPOINT_2_HOST"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "RP_ENDPOINT_2_PORT"
              value: "10002"
            - name: "RP_ENDPOINT_AKKA_MGMT_HTTP_BIND_HOST"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "RP_ENDPOINT_AKKA_MGMT_HTTP_BIND_PORT"
              value: "10002"
            - name: "RP_ENDPOINT_AKKA_MGMT_HTTP_HOST"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "RP_ENDPOINT_AKKA_MGMT_HTTP_PORT"
              value: "10002"
            - name: "RP_ENDPOINT_AKKA_REMOTE_BIND_HOST"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "RP_ENDPOINT_AKKA_REMOTE_BIND_PORT"
              value: "10001"
            - name: "RP_ENDPOINT_AKKA_REMOTE_HOST"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "RP_ENDPOINT_AKKA_REMOTE_PORT"
              value: "10001"
            - name: "RP_ENDPOINT_HTTP_BIND_HOST"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "RP_ENDPOINT_HTTP_BIND_PORT"
              value: "10000"
            - name: "RP_ENDPOINT_HTTP_HOST"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "RP_ENDPOINT_HTTP_PORT"
              value: "10000"
            - name: "RP_JAVA_OPTS"
              value: "-Dconfig.resource=rp-application.conf -Dakka.discovery.method=kubernetes-api -Dakka.management.cluster.bootstrap.contact-point-discovery.effective-name=chirpservice -Dakka.management.cluster.bootstrap.contact-point-discovery.required-contact-point-nr=2 -Dakka.discovery.kubernetes-api.pod-label-selector=appName=%s -Dcom.lightbend.platform-tooling.service-discovery.external-service-addresses.cas_native.0="
            - name: "RP_KUBERNETES_POD_IP"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "RP_KUBERNETES_POD_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.name"
            - name: "RP_MODULES"
              value: "akka-cluster-bootstrapping,akka-management,common,play-http-binding,service-discovery,status"
            - name: "RP_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
            - name: "RP_PLATFORM"
              value: kubernetes
          ports:
            - containerPort: 10000
              name: http
            - containerPort: 10001
              name: "akka-remote"
            - containerPort: 10002
              name: "akka-mgmt-http"
          volumeMounts: []
          command:
            - "/rp-start"
          args:
            - "bin/chirp-impl"
          readinessProbe:
            httpGet:
              path: "/platform-tooling/ready"
              port: "akka-mgmt-http"
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: "/platform-tooling/healthy"
              port: "akka-mgmt-http"
            periodSeconds: 10
            initialDelaySeconds: 60
          resources:
            limits:
              cpu: 0.250000
              memory: 536870912
            requests:
              cpu: 0.250000
              memory: 536870912
      volumes: []
---
apiVersion: v1
kind: Service
metadata:
  labels:
    appName: chirpservice
  name: chirpservice
spec:
  ports:
    - name: http
      port: 10000
      protocol: TCP
      targetPort: 10000
    - name: "akka-remote"
      port: 10001
      protocol: TCP
      targetPort: 10001
    - name: "akka-mgmt-http"
      port: 10002
      protocol: TCP
      targetPort: 10002
  selector:
    appName: chirpservice
```

This is generated by running:

```bash
rp generate-kubernetes-resources "chirp-impl:1.0.0-SNAPSHOT" \
  --generate-pod-controllers --generate-services \
  --env JAVA_OPTS="-Dplay.http.secret.key=$chirp_secret -Dplay.filters.hosts.allowed.0=$allowed_host" \
  --external-service "cas_native=$cassandra_svc" \
  --pod-controller-replicas 2
```

Note that I didn't define `chirp_secret`, `allowed_host`, or `cassandra_svc` in my test, so these are empty strings in the generated configuration, but that's not relevant to this issue.
